// examples/vue/src/AetherShellShowcase.vue
<script setup lang="ts">
import { ref } from "vue";

import { createGfmEditorPlugins } from "@aether-md/example-shared";
import { SHOWCASE_MARKDOWN } from "@aether-md/example-shared/showcase-markdown";
import { AetherEditorContent, AetherEditorRoot, AetherMorphingDocument } from "@aether-md/vue";

import MarkdownPreview from "./MarkdownPreview.vue";

const markdown = ref(SHOWCASE_MARKDOWN);
const renderCount = ref(0);
const plugins = createGfmEditorPlugins();
const mode = ref<"morphing" | "content">("morphing");

function handleChange(next: string) {
  markdown.value = next;
}
</script>

<template>
  <main class="example" data-testid="aether-vue-showcase">
    <nav class="shell-switcher" aria-label="Vue shell">
      <button
        type="button"
        class="shell-switcher-button"
        data-testid="shell-mode-morphing"
        :aria-pressed="mode === 'morphing'"
        @click="mode = 'morphing'"
      >
        AetherMorphingDocument
      </button>
      <button
        type="button"
        class="shell-switcher-button"
        data-testid="shell-mode-content"
        :aria-pressed="mode === 'content'"
        @click="mode = 'content'"
      >
        AetherEditorContent (legacy)
      </button>
    </nav>
    <button type="button" class="shell-toolbar-button" @click="renderCount += 1">
      Force parent rerender ({{ renderCount }})
    </button>
    <AetherEditorRoot :plugins="plugins" :value="markdown" :on-change="handleChange">
      <section
        v-if="mode === 'morphing'"
        class="example-editor"
        data-testid="aether-morphing-shell"
      >
        <AetherMorphingDocument />
        <MarkdownPreview />
      </section>
      <section v-else class="example-editor" data-testid="aether-vue-basic-shell">
        <AetherEditorContent />
        <MarkdownPreview />
      </section>
    </AetherEditorRoot>
  </main>
</template>

// examples/react/src/aether-shell-showcase.tsx
import { useState } from "react";

import { createGfmEditorPlugins } from "@aether-md/example-shared";
import {
  E2EProbes,
  MoveListBlockButton,
  ParentRerenderButton,
} from "@aether-md/example-shared/e2e-probes";
import { SHOWCASE_MARKDOWN } from "@aether-md/example-shared/showcase-markdown";
import { AetherEditorContent, AetherEditorRoot, AetherMorphingDocument } from "@aether-md/react";

export type ReactShellMode = "content" | "morphing";

const SHELLS: { mode: ReactShellMode; label: string }[] = [
  { mode: "morphing", label: "AetherMorphingDocument" },
  { mode: "content", label: "AetherEditorContent (legacy)" },
];

export function AetherShellShowcase() {
  const [mode, setMode] = useState<ReactShellMode>("morphing");
  const [markdown, setMarkdown] = useState(SHOWCASE_MARKDOWN);
  const [renderCount, setRenderCount] = useState(0);

  return (
    <main className="example" data-testid="aether-shell-showcase">
      <nav className="shell-switcher" aria-label="React shell">
        {SHELLS.map(({ mode: shellMode, label }) => (
          <button
            key={shellMode}
            type="button"
            className="shell-switcher-button"
            data-testid={`shell-mode-${shellMode}`}
            aria-pressed={mode === shellMode}
            onClick={() => setMode(shellMode)}
          >
            {label}
          </button>
        ))}
      </nav>

      <AetherEditorRoot plugins={createGfmEditorPlugins()} value={markdown} onChange={setMarkdown}>
        {mode === "content" ? (
          <section className="example-editor" data-testid="aether-react-basic-shell">
            <AetherEditorContent />
          </section>
        ) : (
          <section className="example-editor" data-testid="aether-morphing-shell">
            <AetherMorphingDocument />
          </section>
        )}
        <div className="e2e-toolbar">
          <ParentRerenderButton
            renderCount={renderCount}
            onRerender={() => setRenderCount((count) => count + 1)}
          />
          {mode === "morphing" ? <MoveListBlockButton /> : null}
        </div>
        <E2EProbes markdown={markdown} enableMoveBlock={mode === "morphing"} />
      </AetherEditorRoot>
    </main>
  );
}
